# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sveltin < Formula
  desc "A powerful CLI for your next SvelteKit powered static website."
  homepage "https://sveltin.io"
  version "0.11.0"
  license "Apache-2.0"

  depends_on "git"
  depends_on "node"

  on_macos do
    if Hardware::CPU.intel?
      url "http://github.com/sveltinio/sveltin/releases/download/v0.11.0/sveltin_0.11.0_Darwin-x86_64.tar.gz"
      sha256 "2e3c75cbac4728f3a66e8f059891761d42bca1f32c1e9fc06d873776ef2ebba3"

      def install
        bin.install "sveltin"
      end
    end
    if Hardware::CPU.arm?
      url "http://github.com/sveltinio/sveltin/releases/download/v0.11.0/sveltin_0.11.0_Darwin-arm64.tar.gz"
      sha256 "c12c25e78905bcf6e890bba0e5e0dafc8a732f269fd0bba0e8037163ec3782e4"

      def install
        bin.install "sveltin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/sveltinio/sveltin/releases/download/v0.11.0/sveltin_0.11.0_Linux-arm64.tar.gz"
      sha256 "b7656b12cf8e181bf370f190dda19f504bd14c57a20ba15d50dce54365830be4"

      def install
        bin.install "sveltin"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/sveltinio/sveltin/releases/download/v0.11.0/sveltin_0.11.0_Linux-x86_64.tar.gz"
      sha256 "1f45cb7322a5f8ec87ee30e776c38acbee183b54a77d26106301181a6bca83d3"

      def install
        bin.install "sveltin"
      end
    end
  end

  def caveats
    <<~EOS
      To get started run: `sveltin -h` or visit https://docs.sveltin.io
    EOS
  end
end
