# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sveltin < Formula
  desc "A powerful CLI for your next SvelteKit powered static website."
  homepage "https://sveltin.io"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "http://github.com/sveltinio/sveltin/releases/download/v0.1.0/sveltin_0.1.0_Darwin-arm64.tar.gz"
      sha256 "b797d8a68078c44726006e53bb8b4066dcc9c3eb238421fbbed66e06e9580abc"

      def install
        bin.install "sveltin"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/sveltinio/sveltin/releases/download/v0.1.0/sveltin_0.1.0_Darwin-x86_64.tar.gz"
      sha256 "aea1d156f706c8c75382d9229a70854119b901806ec9d4db5a2006a2abee03e8"

      def install
        bin.install "sveltin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://github.com/sveltinio/sveltin/releases/download/v0.1.0/sveltin_0.1.0_Linux-x86_64.tar.gz"
      sha256 "73a653ae28592e03e38339dcc7538ef8705ec1d335aeedc18f676fb6389831cd"

      def install
        bin.install "sveltin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/sveltinio/sveltin/releases/download/v0.1.0/sveltin_0.1.0_Linux-arm64.tar.gz"
      sha256 "389a1277ed779339035be9ee90a00b919fbe37b0358b0cef7b5ced69c0772aac"

      def install
        bin.install "sveltin"
      end
    end
  end

  depends_on "git"

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
